from django.urls import path
from . import views

urlpatterns=[
    path("",views.index),
    path('admin_login/',views.admin_login),
    path('admin_login_check/',views.admin_login_check),
    path('admin_dashboard/',views.admin_dashboard),
    path("supplier_request/",views.supplier_request),
    path("save_supplier_request/",views.save_supplier_request),
    path("view_supplier_request/",views.view_supplier_request),
    path("approve_request/<id>",views.approve_request),
    path("save_approve_request/<id>",views.save_approve_request),
    path("reject_request/<id>",views.reject_request),
    path("user_login/",views.user_login),
    path("user_registration/",views.user_registration),
    path("user_login_check/",views.user_login_check),
    path("supplier_dashboard/",views.supplier_dashboard),
    path("add_material_category/",views.add_material_category),
    path("category_save/",views.category_save),
    path("view_material_category/",views.view_material_category),
    path("add_material/",views.add_material),
    path("material_save/",views.material_save),
    path("save_registration/",views.save_registration),
    path("user_dashboard/",views.user_dashboard),
    path("upload_plan/",views.upload_plan),
    path("send_plan/",views.send_plan),
    path("design_plan/",views.design_plan),
    path("save_design_plan/",views.save_design_plan),
    path("admin_view_plan_details/",views.admin_view_plan_details),
    path("admin_view_uploaded_plan/",views.admin_view_uploaded_plan),
    path("admin_view_plan_details/",views.admin_view_plan_details),
    path("send_plan_to_user/<id>",views.send_plan_to_user),
    path("save_send_plan_user/<id>",views.save_send_plan_user),
    path("uploaded_cost_estimation/<id>",views.uploaded_cost_estimation),
    path("save_cost_uploaded/<id>",views.save_cost_uploaded),
    path("uploaded_plan_cost_user/",views.uploaded_plan_cost_user),
    path("approve_uploaded_cost/<id>",views.approve_uploaded_cost),
    path("reject_uploaded_cost/<id>",views.reject_uploaded_cost),
    path("designed_plan_view/",views.designed_plan_view),
    path("admin_view_design_plan_details/",views.admin_view_design_plan_details),

    path("view_user_designed_plan/<id>",views.view_user_designed_plan),
    path("approve_designed_cost/<id>",views.approve_designed_cost),
    path("admin_set_designed_cost/",views.admin_set_designed_cost),
    path("admin_send_designed_cost/<id>",views.admin_send_designed_cost),
    path("save_design_cost_uploaded/<id>",views.save_design_cost_uploaded),
    path("designed_plan_cost/",views.designed_plan_cost),
    path("designed_plan_payment/<id>",views.designed_plan_payment),
    path("about/",views.about),
    path("contact/",views.contact),
    path("services/",views.services),
    path("user_view_suppliers/",views.user_view_suppliers),
    path("user_view_materials/<id>",views.user_view_materials),
    path("view_material/",views.view_material),
    path("Send_Order/<id>",views.Send_Order),
    path("save_order_request/<id>",views.save_order_request),
    path("my_orders/",views.my_orders),
    path("my_rejected_orders/",views.my_rejected_orders),
    path("my_completed_orders/",views.my_completed_orders),
    path("send_feedback/<id>",views.send_feedback),
    path("save_feedback/<id>",views.save_feedback),
    path("user_view_feedback/",views.user_view_feedback),
    path("supplier_requested_order/",views.supplier_requested_order),
    path("supplier_approve_form/<id>",views.supplier_approve_form),
    path("save_approve_form/<id>",views.save_approve_form),
    path("supplier_view_approved/",views.supplier_view_approved),
    path("supplier_reject_form/<id>",views.supplier_reject_form),
    path("save_reject_form/<id>",views.save_reject_form),
    path("supplier_view_rejected/",views.supplier_view_rejected),
    path("supplier_view_feedback/",views.supplier_view_feedback),
    path("admin_view_orders/",views.admin_view_orders),
    path("admin_view_consumers/",views.admin_view_consumers),
    path("admin_view_feedbacks/",views.admin_view_feedbacks),
    path("pay_online/<id>",views.pay_online),
    path("pay_online_status/<id>",views.pay_online_status),
    path("delete_request/<id>",views.delete_request),





    ]