# Generated by Django 4.1.5 on 2023-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_supplier_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('proof', models.FileField(null=True, upload_to='media')),
                ('dt', models.DateField(null=True)),
                ('tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
