# Generated by Django 4.1.5 on 2023-04-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0004_tbl_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_material',
            name='Thermal_capacity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_material',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
