# Generated by Django 4.1.5 on 2023-04-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0005_tbl_material_thermal_capacity_tbl_material_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('dt', models.DateField(auto_now_add=True, null=True)),
                ('tm', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
