# Generated by Django 4.1.5 on 2023-04-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0008_tbl_design_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_design_plan',
            name='plan',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
