# Generated by Django 4.1.5 on 2023-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0011_tbl_uploaded_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_design_plan',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
