# Generated by Django 4.1.5 on 2023-04-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0012_tbl_design_plan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_cost_designed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.FileField(null=True, upload_to='media')),
                ('cost', models.IntegerField(null=True)),
                ('dt', models.DateField(auto_now_add=True, null=True)),
                ('tm', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructapp.tbl_registration')),
            ],
        ),
    ]
