# Generated by Django 4.1.6 on 2023-04-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0013_final_cost_designed'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_material_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_mobile', models.IntegerField(null=True)),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('Address', models.TextField(max_length=1000, null=True)),
                ('delivery_address', models.TextField(max_length=1000, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('instructions', models.TextField(max_length=1000, null=True)),
                ('total_price', models.IntegerField(max_length=100, null=True)),
                ('reject_reason', models.TextField(max_length=700, null=True)),
                ('delivery_date', models.DateField(default='Not Assigned', max_length=200, null=True)),
                ('dt', models.DateField(auto_now_add=True, null=True)),
                ('tm', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Not Assigned', max_length=100, null=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructapp.tbl_registration')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructapp.tbl_material')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='constructapp.tbl_supplier_request')),
            ],
        ),
    ]
