# Generated by Django 4.1.6 on 2023-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0014_tbl_material_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_material_orders',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='tbl_material_orders',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='tbl_material_orders',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_material_orders',
            name='flat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_material_orders',
            name='landmark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_material_orders',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
