# Generated by Django 4.1.6 on 2023-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0015_remove_tbl_material_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_material_orders',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
