# Generated by Django 4.1.6 on 2023-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0016_tbl_material_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_material_orders',
            name='delivery_date',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
