# Generated by Django 4.1.5 on 2023-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0017_alter_tbl_material_orders_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_material_orders',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
