# Generated by Django 5.0 on 2024-02-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructapp', '0019_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_supplier_request',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_supplier_request',
            name='licence_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
